// This script's automatically generated by EnumGenerator.cs
namespace CustomResourceManagement
{
	public enum Materials{
		DefaultMaterial,
		GreenMaterial,
		RedMaterial,
	}
	public struct Prefabs{
		public enum Effect{
			MoveMarker,
			SelectionIndicator,
		}
		public struct Playable{
			public enum Building{
				BuildingA,
				BuildingB,
				BuildingC,
				GoldMine,
				Headquarters,
				Tree,
			}
			public enum Unit{
				Swordsman,
				Worker,
			}
		}
		public enum UI{
			HealthTracker,
			SelectionBox,
		}
	}
}

