// This script's automatically generated by EnumGenerator.cs
namespace CustomResourceManagement
{
	public struct Prefabs{
		public struct Playable{
			public enum Unit{
				Unit_1,
			}
		}
		public enum UI{
			SelectionBox,
		}
	}
}

